CREATE TABLE employees (
  employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR2(30) NOT NULL UNIQUE,
  full_name VARCHAR2(120) NOT NULL,
  job_role VARCHAR2(80) NOT NULL,
  weekly_capacity_hours NUMBER(5,2) DEFAULT 40 NOT NULL CHECK (weekly_capacity_hours > 0),
  active_flag CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active_flag IN ('Y','N'))
);

CREATE TABLE projects (
  project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code VARCHAR2(30) NOT NULL UNIQUE,
  project_name VARCHAR2(160) NOT NULL,
  owner_name VARCHAR2(120) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK(status IN ('PLANNED','ACTIVE','ON_HOLD','CLOSED')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  CONSTRAINT ck_project_dates CHECK(end_date >= start_date)
);

CREATE TABLE allocation_requests (
  allocation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id NUMBER NOT NULL REFERENCES employees(employee_id),
  project_id NUMBER NOT NULL REFERENCES projects(project_id),
  allocation_pct NUMBER(5,2) NOT NULL CHECK(allocation_pct > 0 AND allocation_pct <= 100),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL CHECK(status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')),
  requested_by VARCHAR2(120) NOT NULL,
  approved_by VARCHAR2(120),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_allocation_dates CHECK(end_date >= start_date)
);

CREATE TABLE allocation_events (
  event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_id NUMBER NOT NULL REFERENCES allocation_requests(allocation_id),
  event_type VARCHAR2(30) NOT NULL,
  actor VARCHAR2(120) NOT NULL,
  event_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  comments VARCHAR2(500)
);

CREATE INDEX ix_alloc_employee_dates ON allocation_requests(employee_id,start_date,end_date);
CREATE INDEX ix_alloc_project ON allocation_requests(project_id);
